version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: postgres-jazida
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: pokemon_db
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
    api:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: pokemon_api
        restart: always
        command: [ "npm", "run", "dev" ]
        depends_on:
            - postgres
        ports:
            - "3001:3001"
        environment:
            DATABASE_URL: "postgresql://matheus:matheus@postgres:5432/pokemon_db?schema=public"
            NODE_ENV: "development"
        volumes:
            - ./:/usr/app
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
